[tool.poetry]
name = "fireguard-api"
version = "0.1.0"
description = ""
authors = ["Patrick St√ºnkel <webminz@googlemail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.8"}
minio = "^7.2.15"
psycopg2-binary = "^2.9.10"
<<<<<<< HEAD
=======
dynamic-frcm = "^1.0.1"
python-dotenv = "^1.1.0"

>>>>>>> dfea90a9a9ef16bdcddb3459f04839b73a8aeb4f

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
